repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: python -m isort
        types_or: [python, pyi]
        require_serial: true
      - id: black
        name: black
        language: system
        entry: python -m black
        types_or: [python, pyi]
        require_serial: true
      - id: lint
        name: lint
        language: system
        entry: python -m flake8
        files: ^src/.*\.py$
        require_serial: true
      - id: typecheck
        name: typecheck
        language: system
        entry: python -m mypy
        files: ^src/.*\.py$
        require_serial: true
